config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :dishes
  get 'trays/:id' => "trays#show", as: "tray"
  delete 'trays/:id' => "trays#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  get 'thank_you' => "orders#thank_you", as: "thank_you"
  delete 'line_items/:id' => "line_items#destroy"

  resources :dishes  
  resources :orders
  
  root to: "dishes#index"
  
  namespace :admin do
    root to: "dishes#index"
    resources :dishes
    resources :orders
  end
end

app/models/tray.rb
class Tray < ApplicationRecord
  has_many :line_items
  has_many :dishes, through: :line_items
  
  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/controllers/trays_controller.rb
class TraysController < ApplicationController
  def show
    @tray = @current_tray
  end

  def destroy
    @tray = @current_tray
    @tray.destroy
    session[:tray_id] = nil
    redirect_to root_path
  end
end

app/helpers/trays_helper.rb
module TraysHelper
end

app/views/trays/show.html.erb
<div class="container">
  <div class="row py-5">
    <div class="col-md-12">
      <h5 class="py-4">My Tray</h5>
      <ul class="list-group">
        <% @tray.line_items.each do |line_item| %>
          <li class="list-group-item">
            <div class="media">
              <svg class="bd-placeholder-img mr-3" width="64" height="64" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 64x64">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#868e96"></rect>
                <text x="50%" y="50%" fill="#dee2e6" dy=".3em">64x64</text>
              </svg>
              <div class="media-body">
                <div>
                  <h6 class="my-0"><%= line_item.dish.name %></h6>
                  <small class="text-muted">Brief description</small>
                </div>
                <span class="text-muted">
                  <small><%= number_to_currency(line_item.dish.price) %> &times; <%= line_item.quantity %></small>
                  <small><%= number_to_currency(line_item.total_price) %></small>
                </span>
              </div>
              <div class="input-group mt-3" style="width: 138px;">
                <div class="input-group-prepend">
                  <%= link_to "-", line_item_reduce_path(:id => line_item), method: :post, class: "input-group-text" %>
                </div>
                <input type="text" class="text-center" aria-label="Amount (to the nearest dollar)" style="width: 70px;" value="<%= line_item.quantity %>">
                <div class="input-group-append">
                  <%= link_to "+", line_item_add_path(:id => line_item), method: :post, class: "input-group-text" %>
                </div>
              </div>
              <%= link_to "&times;".html_safe, line_item_path(line_item), method: :delete, class: "btn btn-danger mt-3 ml-2" %>
              <!-- -->
            </div>
          </li>
        <% end %>
        <li class="list-group-item py-4 border-0">Sub-total <%= number_to_currency(@tray.sub_total) %></li>
      </ul>
      <%= link_to "Proceed to checkout", new_order_path, class: "btn btn-primary my-4" %><br>
      <%= link_to "Empty cart", tray_path(@current_tray), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  </div>
</div>