config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :dishes
  get 'trays/:id' => "trays#show", as: "tray"
  delete 'trays/:id' => "trays#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  get 'thank_you' => "orders#thank_you", as: "thank_you"
  delete 'line_items/:id' => "line_items#destroy"

  resources :dishes  
  resources :orders
  
  root to: "dishes#index"
  
  namespace :admin do
    root to: "dishes#index"
    resources :dishes
    resources :orders
  end
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :line_items, dependent: :destroy
   belongs_to :user
   enum status: %i[pending on_process paid delivered]
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :set_admin_order, only: [:show, :edit, :update, :destroy]

  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @orders = Order.all
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Admin::Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders
  # POST /admin/orders.json
  def create
    @admin_order = Admin::Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to @admin_order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to @admin_order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1
  # DELETE /admin/orders/1.json
  def destroy
    @admin_order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Admin::Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_order_params
      params.fetch(:admin_order, {})
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
  
  def create
    pry
    @order = current_user.order.build(order_params)
    @current_tray.line_items.each do |item|
      @order.line_items << item
      item.tray_id = nil
    end
    pry
    respond_to do |format|
      if @order.save!
        Tray.destroy(session[:tray_id])
        session[:tray_id] = nil
        format.html { redirect_to thank_you_path }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def new
    @order = Order.new
  end
  
  private
  def order_params
    params.require(:order).permit(:name, :email, :address, :pickup_time, :first_name, :last_name, :address_line_1, :address_line_2, :province, :city, :mobile_number, :zip, :note)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: admin_order, local: true) do |form| %>
  <% if admin_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul>
      <% admin_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Admin Order</h1>

<%= render 'form', admin_order: @admin_order %>

<%= link_to 'Show', @admin_order %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="py-3">Orders</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Status</th>
      <th scope="col">Amount</th>
      <th scope="col">Change Status</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <th scope="row"><%= order.id %></th>
        <td><%= order.created_at.strftime("%B %d, %Y") %></td>
        <td><%= order.status %></td>
        <td>
            <% order.line_items.each do |item| %>
              <span><%= item.dish.name %></span>
            <% end %>
        </td>
        <td>
          <button class="btn btn-md">Change Status</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/new.html.erb
<h1>New Admin Order</h1>

<%= render 'form', admin_order: @admin_order %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_order_path(@admin_order) %> |
<%= link_to 'Back', admin_orders_path %>