config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :dishes
  get 'trays/:id' => "trays#show", as: "tray"
  delete 'trays/:id' => "trays#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  get 'thank_you' => "orders#thank_you", as: "thank_you"
  delete 'line_items/:id' => "line_items#destroy"

  resources :dishes  
  resources :orders
  
  root to: "dishes#index"
  
  namespace :admin do
    root to: "dishes#index"
    resources :dishes
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :dish
  belongs_to :tray
  
  def total_price
    if valid_quantity_and_price?
      quantity.to_s.to_d * dish.price.to_s.to_d
    else
      0.0
    end
  end

  def valid_quantity_and_price?
    !quantity.to_s.strip.empty? && !dish.price.to_s.strip.empty?
  end
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :line_items, dependent: :destroy
   belongs_to :user
   enum status: %i[pending on_process paid delivered]
end

app/models/tray.rb
class Tray < ApplicationRecord
  has_many :line_items
  has_many :dishes, through: :line_items
  
  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders
  
  enum role: %i[member admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SetTray
  
  before_action :authenticate_user!
  before_action :verify_role!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_root_path
    else
      root_path
    end
  end
  
  def verify_role!
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/concerns/set_tray.rb
module SetTray
  extend ActiveSupport::Concern
  
  included do
    before_action :set_cart
  end
  
  def set_cart
    if session[:tray_id]
      tray = Tray.find_by(id: session[:tray_id])
      tray.present? ? (@current_tray = tray) : (session[:tray_id] = nil)
    end
    return unless session[:tray_id].nil?
    @current_tray = Tray.create(user_id: nil)
    session[:tray_id] = @current_tray.id
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.all
  end

  def new
  end
  
  def show
  end

  def edit
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dishes = Dish.all
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    dish = Dish.find(params[:dish_id])
    add_items_to_tray(dish)
    respond_to do |format|
      if @line_item.save!
        format.json { head :no_content }
        format.js {}
        format.html { redirect_to root_path }
      else
        format.html { render :new, notice: 'Error adding product to basket!' }
      end
    end
  end
  
  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to tray_path(@current_tray)
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.quantity -= 1
    end
    @line_item.save
    redirect_to tray_path(@current_tray)
  end
  
  private
  
  def add_items_to_tray(dish)
    if @current_tray.dishes.include?(dish)
      @line_item = @current_tray.line_items.find_by(dish_id: dish)
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.tray = @current_tray
      @line_item.dish = dish
      @line_item.quantity = 1
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
  
  def create
    pry
    @order = current_user.order.build(order_params)
    @current_tray.line_items.each do |item|
      @order.line_items << item
      item.tray_id = nil
    end
    pry
    respond_to do |format|
      if @order.save!
        Tray.destroy(session[:tray_id])
        session[:tray_id] = nil
        format.html { redirect_to thank_you_path }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def new
    @order = Order.new
  end
  
  private
  def order_params
    params.require(:order).permit(:name, :email, :address, :pickup_time, :first_name, :last_name, :address_line_1, :address_line_2, :province, :city, :mobile_number, :zip, :note)
  end
end

app/controllers/trays_controller.rb
class TraysController < ApplicationController
  def show
    @tray = @current_tray
  end

  def destroy
    @tray = @current_tray
    @tray.destroy
    session[:tray_id] = nil
    redirect_to root_path
  end
end

app/helpers/admin/dishes_helper.rb
module Admin::DishesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/trays_helper.rb
module TraysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Scrambledeggs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? && current_user.admin? %>
      <div class="d-flex" id="wrapper">
        <%= render "shared/admin/sidebar" %>
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <%= render "shared/admin/header" %>
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
      <% if user_signed_in? %>
        <%= render "shared/header" %>
      <% end %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Scrambledeggs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
      </ul>
      <% if current_user.member? %>
        <div class="dropdown">
          <button class="btn btn-link" type="button" id="dropdown-tray" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Tray <span id="total_cart_items">(<%= @current_tray.line_items.count %>)</span>
          </button>
          <ul class="dropdown-menu cart-view p-0 border-0 dropdown-menu-right p-0" aria-labelledby="dropdown-tray" style="width: 300px;">
            <li class="dropdown-item p-0 border-0">
              <ul class="list-group" id="tray-line-items">
                <% @current_tray.line_items.each do |line_item| %>
                  <%= render "line_items/line_item", line_item: line_item %>
                <% end %>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Total (USD)</span>
                  <strong><%= number_to_currency(@current_tray.sub_total)  %></strong>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <%= link_to "View My Tray", tray_path(@current_tray), class: "btn btn-block btn-primary" %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      <% end %>
      <div class="dropdown">
        <button class="btn btn-link" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.first_name %> <%= current_user.last_name %>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button">Action</button>
          <button class="dropdown-item" type="button">Another action</button>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.first_name %> <%= current_user.last_name %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/admin/_sidebar.html.erb
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">Backoffice </div>
  <div class="list-group list-group-flush">
    <%= link_to "Dashboard", root_path, class: "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Dishes", admin_dishes_path, class: "list-group-item list-group-item-action bg-light" %>
    <%= link_to "Orders", admin_orders_path, class: "list-group-item list-group-item-action bg-light" %>
  </div>
</div>